@startuml "Use Cases Admin"
    left to right direction
    :Admin: --> (Search client)
    :Admin: --> (Create client)
    :Admin: --> (Edit client)
    :Admin: --> (Remove client)
    :Admin: --> (View client information)
    :Admin: --> (Search book)
    :Admin: --> (Create book)
    :Admin: --> (Edit book)
    :Admin: --> (Remove book)
    :Admin: --> (View books information)
    :Admin: --> (Search author)
    :Admin: --> (Create author)
    :Admin: --> (Edit author)
    :Admin: --> (Remove author)
    :Admin: --> (View author information)
    :Admin: --> (Search librarian)
    :Admin: --> (Create librarian)
    :Admin: --> (Edit librarian)
    :Admin: --> (Remove librarian)
    :Admin: --> (View librarian information)
    :Admin: --> (View lent books)
    :Admin: --> (View overdue books)
    :Admin: --> (Pay client fine)
@enduml