name: Library Management System CI Pipeline for Development Environment

on:
  push:
    branches-ignore:
      - main
      - docs

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Git Leaks Scan
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  backend:
    name: LMS Backend
    runs-on: ubuntu-latest
    needs: [ security ]
    strategy:
      matrix:
        node: [ '24.x', '26.x' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: backend
        run: npm ci